### ISSUE TITLE
WCF

### ISSUE THREAD

**Issue by iasimin** [pmaxim98/TSP.NET-Laboratories#1]
Clientul nu trebuie sa faca referinta la alte proiecte.
Refaceti proiectul! Este eronat clientul.

**Comment by pmaxim98** [comment]
@iasimin Am scos referintele. :) Multumesc.

Commit-ul in cauza: 
https://github.com/pmaxim98/TSP.NET-Laboratories/commit/9c519549816558cde0a48ada2f3205f96c4747b7

O imagine cu aplicatia si serverul: 
![image](https://user-images.githubusercontent.com/24731804/77536148-87304180-6ea4-11ea-9d12-9cca6d113cc8.png)
